using Famick.HomeManagement.Messaging.DTOs;
using Famick.HomeManagement.Core.Interfaces;
using Famick.HomeManagement.Messaging.Interfaces;
using Famick.HomeManagement.Domain.Enums;
using Microsoft.Extensions.Logging;

namespace Famick.HomeManagement.Messaging.Services;

/// <summary>
/// Sends rendered messages via email using the existing IEmailService transport.
/// </summary>
public class EmailMessageTransport : IMessageTransport
{
    private readonly IEmailService _emailService;
    private readonly ILogger<EmailMessageTransport> _logger;

    public TransportChannel Channel => TransportChannel.EmailHtml;

    public EmailMessageTransport(
        IEmailService emailService,
        ILogger<EmailMessageTransport> logger)
    {
        _emailService = emailService;
        _logger = logger;
    }

    public async Task SendAsync(RenderedMessage message, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(message.ToEmail))
        {
            _logger.LogWarning("Cannot send email: no recipient address for message type {Type}", message.Type);
            return;
        }

        if (string.IsNullOrEmpty(message.HtmlBody) || string.IsNullOrEmpty(message.Subject))
        {
            _logger.LogWarning("Cannot send email: missing HTML body or subject for message type {Type}", message.Type);
            return;
        }

        var isTransactional = message.Type.IsTransactional();

        if (isTransactional)
        {
            await _emailService.SendRawEmailAsync(
                message.ToEmail,
                message.Subject,
                message.HtmlBody,
                message.TextBody ?? string.Empty,
                cancellationToken);
        }
        else
        {
            // Notification emails get RFC 2369 List-Unsubscribe + RFC 8058 One-Click headers.
            // The unsubscribe URL is pre-generated by MessageService and already in the HTML footer.
            await _emailService.SendNotificationEmailAsync(
                message.ToEmail,
                message.Subject,
                message.HtmlBody,
                message.TextBody ?? string.Empty,
                message.UnsubscribeUrl ?? string.Empty,
                cancellationToken);
        }
    }
}
